#!/usr/bin/env bash
# yuki_status.sh - Lightweight Yuki status check
# Usage: yuki_status.sh (or alias to 'yuki' for quick checks)

echo "🚦 Yuki Status Check - Lightweight Overview"
echo "Last updated: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "📊 Quick Status"
echo "  • Yuki: Active & Ready (Persistent Engineering Assistant)"
echo "  • Project Integration: Maintained (Dori files preserved)"
echo "  • Primary Focus: Check for repo changes & task updates"
echo ""
echo "🔍 Recommended Quick Checks (Run these first):"
echo "  1. git status --porcelain - Check for uncommitted changes"
echo "  2. cat .ai-context/TASKS.md \| grep -E '^\* \[ \]' \| head -5 - See top 5 open tasks"
echo "  3. ls -la .claude/projects/*/memory/MEMORY.md 2>/dev/null \| head -1 - Verify memory system active"
echo ""
echo "🚨 Critical Alerts (Address ASAP if present)"
echo "  • [ ] Model-data mismatch: constants.py vs labels.json (5 signs only)"
echo "  • [ ] Duplicate import in app.py line 87: \"from constants import SIGN_INFO\""
echo "  • [ ] Uncommitted binary files in git (should be in .gitignore)"
echo ""
echo "📈 Progress at a Glance"
echo "  • ✅ Completed: 9 tasks (including notebook move, cleanup, memory systems)"
echo "  • ⏳ Open: 18 tasks remaining"
echo "  • 🔥 Next Priority: Fix critical model-data mismatch (constants.py)"
echo ""
echo "💡 Yuki Usage Tips"
echo "  • For lightweight check: Run this script (yuki_status.sh)"
echo "  • For full task review: cat .ai-context/TASKS.md"
echo "  • For technical details: Check memory files in .claude/projects/*/memory/"
echo "  • For session prep: ./scripts/yuki-dori-ready.sh --quick (if needed)"
echo ""
echo "🧠 Yuki Principle"
echo "  > Only run what's necessary. Check changes first, then act."
echo "  > Integrate only when repo changes detected"
echo "  > Run preprocessing only for specific requested tasks"
echo "  > Token conservation through targeted activation"
echo ""
echo "---"
echo "This is a lightweight status check. For full Yuki engagement, specify a clear task or query."